### ISSUE TITLE
Reward difference on 2v2 and 3v3

### ISSUE THREAD

**Issue by Mamaro89** [azerothcore/mod-bg-reward#13]
Guys is it possible to reward differently 2v2 and 3v3?

i want to give 2 items for wining a 2v2 match, and 3 items for winning a 3v3 match, to encourage ppl to join 3v3.
Still, when they lose a match, 2v2 or 3v3, they get only 1 item.
Is it possible to make?  

I tried a solution with a new item, a bag.  Inside the bag there is the right ammount of items, but still.. the loser will get the same bag, bcz i cant set the loser's item, it is the same, only ammount changes.. 

Pls if you have any idea on how to implement that, or if you could do that, i'll be very appreciated.  

thanks a lot

**Comment by Helias** [comment]
@IntelligentQuantum

**Comment by IntelligentQuantum** [comment]
https://paste.ubuntu.com/p/vPQn45qWsK/

**Comment by Helias** [comment]
@IntelligentQuantum I think you could make a PR for this :P
